language: objective-c

matrix:
  include:
    - osx_image: xcode13.2

before_install:
  - rvm install 3.2.2

install:
  - gem install activesupport -v 6.1.7.6
  - gem install cocoapods

script:
  - pod update
  - pod lib lint --allow-warnings
  - xcodebuild clean build -workspace ENPushDestination.xcworkspace -scheme ENPushDestination CODE_SIGNING_REQUIRED=NO SUPPORTS_MACCATALYST=NO -destination "generic/platform=iOS Simulator"
  - xcodebuild test -workspace ENPushDestination.xcworkspace -scheme ENPushDestinationTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2';

